CC = clang++
FILES = diversify.cpp private/storedata.cpp private/ymath.cpp private/dataframe.cpp private/date.cpp private/frontieralgo.cpp private/risktopointalgo.cpp 


test: $(FILES)
	$(CC) $(FILES) -o Diversify -std=c++11
